### PR TITLE
Suppress "Lifting the server siege..." in quiet mode

### PR DESCRIPTION
**Pull request by bbakersmith**
Per discussion: https://github.com/JoeDog/siege/pull/167#issuecomment-583949130

### CODE REVIEW

**Comment by JoeDog** [comment]
I don't know what happened. I merged this and lost your first one.

**Comment by bbakersmith** [comment]
@JoeDog here ya go https://github.com/JoeDog/siege/pull/167

**Comment by JoeDog** [comment]
I got it worked out. I pulled files from your branch and backed them into main manually.

What name and address do you want in the ChangeLog

**Comment by bbakersmith** [comment]
Great, thanks!

Ben Baker-Smith <ben@baker-smith.net>

**Pull request merged**
