### PR TITLE
Added PATCH method support

### PR DESCRIPTION
**Pull request by david-moran**

### CODE REVIEW

**Comment by JoeDog** [comment]
David,

Looks good. What's an easy way for me to test PATCH?

Jeff

**Comment by david-moran** [comment]
Hi Joe,

You can use http://jsonplaceholder.typicode.com, it's a mockups site, for example, using curl:

Doing a GET request you can see all values for all fields
```
[SRV]root@control:~
#> curl https://jsonplaceholder.typicode.com/posts/1
{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
```

If you want to apply a patch you only need to do:
```
[SRV]root@control:~
#> curl -X PATCH https://jsonplaceholder.typicode.com/posts/1 --data title=hello+world
{
  "userId": 1,
  "id": 1,
  "title": "hello world",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}[SRV]root@control:~
#>
```
As you can see in the response title was modified.

I've tested it on siege using siege and wireshark:

Siege launch:
```
[SRV]root@control:~/siege/src
#> ./siege -v   -c1 -r1  'http://jsonplaceholder.typicode.com/posts/1 PATCH title=hello+world'
** SIEGE 4.0.3rc1
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.51 secs:     180 bytes ==> PATCH http://jsonplaceholder.typicode.com/posts/1

Transactions:                      1 hits
Availability:                 100.00 %
Elapsed time:                   1.52 secs
Data transferred:               0.00 MB
Response time:                  0.51 secs
Transaction rate:               0.66 trans/sec
Throughput:                     0.00 MB/sec
Concurrency:                    0.34
Successful transactions:           1
Failed transactions:               0
Longest transaction:            0.51
Shortest transaction:           0.51

LOG FILE: /usr/local/var/log/siege.log
You can disable this log file notification by editing
/root/.siege/siege.conf and changing 'show-logfile' to false.
[error] unable to create log file: /usr/local/var/log/siege.log: No such file or directory
[SRV]root@control:~/siege/src
#> 

```

response captured by wireshark:
```
{
  "userId": 1,
  "id": 1,
  "title": "hello world",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}
```

**Comment by JoeDog** [comment]
$ ./siege -p  'http://jsonplaceholder.typicode.com/posts/1 PATCH tit >
** SIEGE 4.0.3rc1
** Preparing 1 concurrent users for battle.
The server is now under siege...
PATCH /posts/1 HTTP/1.0
Host: jsonplaceholder.typicode.com
Accept: */*
Accept-Encoding: gzip;deflate
User-Agent: Mozilla/5.0 (unknown-x86_64-linux-gnu) Siege/4.0.3rc1
Connection: close
Content-type: application/x-www-form-urlencoded
Content-length: 17

title=hello+world

{
  "userId": 1,
  "id": 1,
  "title": "hello world",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et
cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt
rem eveniet architecto"
}

Transactions:                      1 hits
Availability:                 100.00 %
Elapsed time:                   1.55 secs
Data transferred:               0.00 MB
Response time:                  1.16 secs
Transaction rate:               0.65 trans/sec
Throughput:                     0.00 MB/sec
Concurrency:                    0.75
Successful transactions:           1
Failed transactions:               0
Longest transaction:            1.16
Shortest transaction:           1.16

**Comment by JoeDog** [comment]
Do you know about using file redirects for POST/PUT/PATCH?

Put your json in a file and do this:

./siege -p  'http://jsonplaceholder.typicode.com/posts/1 PATCH <./haha.json'

BTW: -p/--print is a new feature that's not in your repository. It works
like -g/--get but it prints the page

**Pull request merged**
