### PR TITLE
Implement IPv6 support

### PR DESCRIPTION
**Pull request by florinpapa**
Implemented IPv6 support in src/sock.c. The main modification that needed to be made for this was to replace the deprecated gethostbyname_r with getaddrinfo for platforms that have GLIBC.

### CODE REVIEW

**Comment by florinpapa** [comment]
Added another commit that implements parsing for IPv6 addresses. The convention used for IPv6 addresses is the same used in the Mozilla browser, where IPv6 addresses must be enclosed by square brackets in order to differentiate the address from the port component.

Example: http://[::1]:8000/

**Comment by florinpapa** [comment]
Can I please get feedback on this submission?

I tested the modifications on my side and did not encounter any issues. I used both an IPv6 address (enclosed in square brackets, as described above) and a hostname that resolves to an IPv6 address.

**Comment by shehzadkhawar** [comment]
@florinpapa I tried and it works. It doesn't work with IPv6 raw addresses e.g. http://2001::21:80 but it does work with a domain name (example.com) which is sitting in front of an IPv6 address.

**Comment by florinpapa** [comment]
@shehzadkhawar please see my message on Apr 21. Please enclose the raw IPv6 address in square brackets in order to work. This is the convention use in browsers as well, since otherwise it can be impossible to differentiate the last element of the IPv6 address from the port:
[http://[2001::21]:80](http://[2001::21]:80) or [http://[2001::21:80]](http://[2001::21:80])

I tested ol localhost and it works for [http://[::1]:8000](http://[::1]:8000)

**Comment by JoeDog** [comment]
I've been waiting for somebody to implement this. Have you been able to
test it with name resolution? i.e., the name resolves to an IPv6 address.

::1                   localhost6.localdomain6   localhost6

**Comment by florinpapa** [comment]
I tested with both raw IPv6 address (http://[::1]) and with name resolution and it works for me. Please see terminal output below:
```
florin@flubuntu:~/siege_ipv6/siege_git/src$ ./siege -c 1 -r 1 http://ip6-localhost -v
** SIEGE 4.0.3rc4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.00 secs:     384 bytes ==> GET  /

Transactions:		           1 hits
Availability:		      100.00 %
Elapsed time:		        0.00 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	        0.00 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        0.00
Successful transactions:           1
Failed transactions:	           0
Longest transaction:	        0.00
Shortest transaction:	        0.00

florin@flubuntu:~/siege_ipv6/siege_git/src$ ./siege -c 1 -r 1 http://[::1] -v
** SIEGE 4.0.3rc4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.00 secs:     384 bytes ==> GET  /

Transactions:		           1 hits
Availability:		      100.00 %
Elapsed time:		        0.00 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	        0.00 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        0.00
Successful transactions:           1
Failed transactions:	           0
Longest transaction:	        0.00
Shortest transaction:	        0.00

florin@flubuntu:~/siege_ipv6/siege_git/src$ cat /etc/hosts | grep ip6-localhost
::1     ip6-localhost ip6-loopback
```

**Comment by shehzadkhawar** [comment]
Yes, I acknowledge. It works with both names and IPs.

**Comment by florinpapa** [comment]
@JoeDog - is there anything else you would like to see in this PR to get it merged?

**Comment by JoeDog** [comment]
I was waiting for 4.0.4 to go final before adding this.  I'm looking at it now.  localhost6 works but the IPv6 address for the server does not:

# ./siege -c 1 -r 1 http://[::1]:8080 -v
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 302     0.01 secs:       0 bytes ==> GET  /
HTTP/1.1 200     0.00 secs:    2064 bytes ==> GET  /dashboard/index.html

Transactions:                      2 hits
Availability:                 100.00 %
Elapsed time:                   0.01 secs
Data transferred:               0.00 MB
Response time:                  0.00 secs
Transaction rate:             200.00 trans/sec
Throughput:                     0.20 MB/sec
Concurrency:                    1.00
Successful transactions:           2
Failed transactions:               0
Longest transaction:            0.01
Shortest transaction:           0.00

labas053 # ./siege -c 1 -r 1 http://[fe80::250:56ff:fe9d:395f]:8080 -v
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...
[error] socket: 1300903680 unknown network error.: Invalid argument

**Comment by florinpapa** [comment]
I will try to reproduce this. Are you able to access that URL from your browser?

**Comment by florinpapa** [comment]
@JoeDog you are trying to use the link-local IPv6 address, which doesn't work without the interface identifier (I checked using wget, curl and siege) - https://unix.stackexchange.com/questions/356451/wget-and-curl-an-explicit-ipv6-address

Manually adding a global IPv6 address solves this issue and both siege and wget work fine:
```
florin@flubuntu:~/siege_ipv6/siege_git/src$ sudo ip -6 addr add 2001:0db8:0:f101::1/64 dev enp0s31f6
```
```
florin@flubuntu:~/django_wl/instagram_work/siege_ipv6/siege_git/src$ ./siege -c 1 -r 1 http://[2001:db8:0:f101::1]:8000 -v
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.00 secs:     384 bytes ==> GET  /

Transactions:		           1 hits
Availability:		      100.00 %
Elapsed time:		        1.00 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	        1.00 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        0.00
Successful transactions:           1
Failed transactions:	           0
Longest transaction:	        0.00
Shortest transaction:	        0.00


florin@flubuntu:~/siege_ipv6/siege_git/src$ wget -6 http://[2001:db8:0:f101::1]:8000
--2017-09-11 14:04:15--  http://[2001:db8:0:f101::1]:8000/
Connecting to [2001:db8:0:f101::1]:8000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 612 [text/html]
Saving to: ‘index.html.1’

index.html.1                                         100%[======================================================================================================================>]     612  --.-KB/s    in 0s      

2017-09-11 14:04:15 (258 MB/s) - ‘index.html.1’ saved [612/612]
```
I couldn't get the link-local IPv6 address to work in a browser, in wget or in my implementation even if you specify the interface identifier, while curl works. 
```
florin@flubuntu:~/siege_ipv6/siege_git/src$ wget -6 http://[fe80::701c:3d97:e0d:6148%enp0s31f6]:6969
http://[fe80::701c:3d97:e0d:6148%enp0s31f6]:6969: Invalid IPv6 numeric address.

florin@flubuntu:~/siege_ipv6/siege_git/src$ curl -6 http://[fe80::701c:3d97:e0d:6148%enp0s31f6]:6969
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```
If you consider necessary, I will update the patch to add this functionality, although I think the cleaner approach is to avoid link-local addresses. In this case, I could check for the identifier in the IPv6 address and output a warning for the user to switch to a global or unique local IPv6 address. Please let me know what you think.

**Comment by florinpapa** [comment]
I just checked and the current patch works with link-local IPv6 address with interface identifier as well. Previously it did not work because the "url-escaping" flag was true in ~/.siegerc, causing the IPv6 address
```
http://[fe80::701c:3d97:e0d:6148%enp0s31f6]:8000
```
to become
```
http://[fe80::701c:3d97:e0d:6148%25enp0s31f6]:8000
```

Setting the "url-escaping" flag to false in ~/.siegerc solved the issue and everything works fine:
```
florin@flubuntu:~/siege_ipv6/siege_git/src$ ./siege -c 1 -r 1 http://[fe80::701c:3d97:e0d:6148%enp0s31f6]:8000 -v
** SIEGE 4.0.4
** Preparing 1 concurrent users for battle.
The server is now under siege...
HTTP/1.1 200     0.00 secs:     384 bytes ==> GET  /

Transactions:		           1 hits
Availability:		      100.00 %
Elapsed time:		        1.00 secs
Data transferred:	        0.00 MB
Response time:		        0.00 secs
Transaction rate:	        1.00 trans/sec
Throughput:		        0.00 MB/sec
Concurrency:		        0.00
Successful transactions:           1
Failed transactions:	           0
Longest transaction:	        0.00
Shortest transaction:	        0.00
```
The problem is that the implementation of "url-escaping" parses the entire URL, including hostname and port, while it should only parse the path. Please let me know if I should make any modifications to this PR to get it merged.

**Comment by JoeDog** [comment]
I'm going to push what you sent me but we should only escape the path, not
the host. Can you fix that? I'll merge that right away.  I was holding off
on this change until 4.0.4 was complete.

Jeff

**Comment by florinpapa** [comment]
Thanks for merging this. I will implement parsing the path and create a PR as soon as I have something.

**Comment by amitavi** [comment]
@JoeDog need some help here with the IPv6 stuff. Thanks a lot for Siege in first place. Have been using it for years. Went ahead and installed 4.0.4 but its just not working out for IPv6. It seems you added support for it in 4.0.4rcX versions as can be seen from this. Could you let me know how do i pick up the latest and greatest image that has this fix?


2017/09/11 Florin Papa <https://github.com/florinpapa>
--
13 | * src/sock.c             Added support for IPv6
14 | * src/url.c              Added support for parsing IPv6 addresses
15 | * src/version.c          Version increment: 4.0.4r1

**Comment by duck-tape** [comment]
I am using version 4.0.4
```./bin/siege --version
SIEGE 4.0.4
```

When I attempted to use the tool with a format:
`http://<FQDN>:<port>`
I got en error:
`[error] Host does not have an IP address: <FDQN>`
I assumed this was a IPV6 issue and thus decided to try the IP instead, but when I tried to use the format: 
`http://[AAAA:BBBB:CCCC:DDDD:EEEE:FFFF:GGGG:HHHH]:<port>`
 I get the error:
`[error] Host not found:[AAAA`
and when I attempt to use the format:
`http://AAAA:BBBB:CCCC:DDDD:EEEE:FFFF:GGGG:HHHH:<port>`
I get an error:
`[error] socket: 999999999 network is unreachable.: Network is unreachable`

Any ideas how I can get around this?

**Comment by florinpapa** [comment]
@duck-tape please try a version newer than 4.0.4.

Looking at the commit log for 4.0.4, my IPv6 patch is not included: https://github.com/JoeDog/siege/commits/v4.0.4

Tag v4.0.4r3 has it: https://github.com/JoeDog/siege/commits/v4.0.4r3

**Comment by JoeDog** [comment]
Thanks, Florin.

**Pull request merged**
